version: '3.1'

services:
  mysql:
    # build: ./mysql
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mysql-chillout
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    ports:
      - 3306:3306

  phpmyadmin:
    build: ./phpmyadmin
    depends_on:
    - mysql
    environment:
     - PMA_HOST=mysql
     - MYSQL_ROOT_PASSWORD=root
    ports:
     - 8888:80

